pull_request_rules:
  - name: merge on CI success and 2 approvals
    conditions:
      - "status-success=build"
      - "status-success=license/cla"
      - "#approved-reviews-by>=2"
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
      - "#changes-requested-reviews-by=0"
    actions:
      comment:
        message: "bors r+"
  - name: merge green dependabot PRs
    conditions:
      - "status-success=build"
      - "author:dependabot-preview[bot]"
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
      - head~=^(?!release.*).*$
    actions:
      delete_head_branch:
