on:
  repository_dispatch:
    types:
      - sync-labels
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync labels from coblox/admin
    steps:
      - name: Download label file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REP_TOKEN }}
        run: |
          curl --header 'Authorization: token ${GITHUB_TOKEN}' \
            --header 'Accept: application/vnd.github.v3.raw' \
            --remote-name \
            --location  'https://api.github.com/repos/coblox/admin/contents/.github/labels.yml?ref=85-sync-labels' \
            --output labels.yml
      - name: Sync label locally
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels.yml
