on:
  repository_dispatch:
    types:
      - sync-labels
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync labels from coblox/admin
    steps:
      - name: Download label file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REP_TOKEN }}
        run: |
          curl --header 'Authorization: token ${GITHUB_TOKEN}' \
            --header 'Accept: application/vnd.github.v3.raw' \
            --remote-name \
            --location https://api.github.com/coblox/admin/85-sync-labels/.github/labels.yml -o labels.yml # To be changed to master
      - name: Sync label locally
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: labels.yml
